language: python

services:
  - docker
  
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t stream4good/ youtube-metadata-scrapper
:$TRAVIS_BRANCH .
  - docker push stream4good/ youtube-metadata-scrapper
:$TRAVIS_BRANCH
